config/routes.rb
Rails.application.routes.draw do

  resources :partners
  root 'visitors#index'

  # Auth
  match 'auth/manager', to: 'visitors#manager', via: :post
  match 'auth/legal_person', to: 'visitors#legal_person', via: :post
  match 'auth/physical_person', to: 'visitors#physical_person', via: :post
  match 'auth/logout', to: 'visitors#logout', via: :get

  # Manager
  match 'manager', to: 'manager#index', via: :get

  # Person
  match 'person', to: 'person#index', via: :get

  # Agency
  resources :agencies

  # Account
  resources :accounts

  # Account Operation
  match '/account_operations/new/:account_id/:tipo', to: 'account_operations#new', via: :get, as: :new_account_operation
  match '/account_operations/', to: 'account_operations#create', via: :post, as: :save_account_operation
  match '/account_operations/:id', to: 'account_operations#show', via: :get, as: :account_operations

  # Physical Person
  resources :physical_people

  # Legal Person
  resources :legal_people

  # Address
  match 'addresses/:id', to: 'addresses#show', via: :get, as: :address
  match 'addresses/:id/edit', to: 'addresses#edit', via: :get, as: :edit_address
  match 'addresses/:id', to: 'addresses#update', via: :patch, as: :update_address

end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController

  before_action :authorize_manager
  before_action :set_manager

  def index

  end

  private

  def set_manager
    @manager = Manager.find session[:manager_id]
  end


end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/views/manager/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: manager_path} Início
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: ('active' if controller_name == 'agencies')}= link_to 'Agências', agencies_path
        %li{class: ('active' if controller_name == 'accounts')}= link_to 'Contas', accounts_path
        %li{class: ('active' if controller_name == 'physical_people')}= link_to 'Pessoa Física', physical_people_path
        %li{class: ('active' if controller_name == 'legal_people')}= link_to 'Pessoa Jurídica', legal_people_path
        %li{class: ('active' if controller_name == 'partner')}= link_to 'Sócios', partners_path
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Sair', auth_logout_path

.container-fluid
  = render 'layouts/flash'

app/views/manager/index.html.haml
= render 'navigation'

.container-fluid
  %h1= "Bem vindo #{@manager.login}"