config/routes.rb
Rails.application.routes.draw do

  resources :partners
  root 'visitors#index'

  # Auth
  match 'auth/manager', to: 'visitors#manager', via: :post
  match 'auth/legal_person', to: 'visitors#legal_person', via: :post
  match 'auth/physical_person', to: 'visitors#physical_person', via: :post
  match 'auth/logout', to: 'visitors#logout', via: :get

  # Manager
  match 'manager', to: 'manager#index', via: :get

  # Person
  match 'person', to: 'person#index', via: :get

  # Agency
  resources :agencies

  # Account
  resources :accounts

  # Account Operation
  match '/account_operations/new/:account_id/:tipo', to: 'account_operations#new', via: :get, as: :new_account_operation
  match '/account_operations/', to: 'account_operations#create', via: :post, as: :save_account_operation
  match '/account_operations/:id', to: 'account_operations#show', via: :get, as: :account_operations

  # Physical Person
  resources :physical_people

  # Legal Person
  resources :legal_people

  # Address
  match 'addresses/:id', to: 'addresses#show', via: :get, as: :address
  match 'addresses/:id/edit', to: 'addresses#edit', via: :get, as: :edit_address
  match 'addresses/:id', to: 'addresses#update', via: :patch, as: :update_address

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :agency
  belongs_to :person

  validates :limite_cheque_esp, presence: true
  validate :incomplete_address

  enum tipo: [:corrente, :poupanca]

  def incomplete_address
    address = person.get_address

    #if [address.rua, address.cidade, address.cep, address.uf.blank?, address.numero.blank?].any?(&:blank?)
    if address.cidade.blank? or address.cep.blank? or address.rua.blank? or address.uf.blank? or address.numero.blank?
      errors.add(:incomplete_address, 'Endereço incompleto')
    end
  end

  def last_operations
    AccountOperation
        .includes(person: [:physical_person, :legal_person])
        .where(account_id: id)
        .order(created_at: :desc)
        .limit(10)
  end

end

app/models/account_operation.rb
class AccountOperation < ActiveRecord::Base

  before_create :set_account_saldo

  belongs_to :account
  belongs_to :person

  enum tipo: [:deposito, :saque]

  def set_account_saldo
    account.update_attribute(:saldo, account.saldo+amount) if deposito?
    account.update_attribute(:saldo, account.saldo-amount) if saque?
  end

end

app/models/address.rb
class Address < ActiveRecord::Base

  #validates :uf, length: { minimum: 2, maximum: 2 }

end

app/models/agency.rb
class Agency < ActiveRecord::Base


  validates :nome, length: { minimum: 3, maximum: 200}
  validates :nome, uniqueness: true
  validates :numero, length: { minimum: 1, maximum: 4}
  validates :numero, uniqueness: true

end

app/models/legal_person.rb
class LegalPerson < ActiveRecord::Base
  belongs_to :person
  belongs_to :address

  before_create :set_physical, :set_address

  validates :nome, length: { minimum: 3, maximum: 200 }
  validates :cnpj, length: { minimum: 13, maximum: 13 }
  validates :cnpj, uniqueness: true

  def set_physical
    self.person = Person.create!(tipo: Person.tipos[:legal])
  end

  def set_address
    self.address = Address.create!
  end

end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  belongs_to :person
  belongs_to :account

  validate :same_account_person
  validate :person_exists
  validate :account_exists

  def same_account_person
    if Partner.where(person_id: person_id).where(account_id: account_id).size > 0
      errors.add(:same_account_person, 'Já existe')
    end
  end

  def person_exists
    if Person.find_by_id(person_id).nil?
      errors.add(:person_not_exists, 'Cliente não encontrado')
    end
  end

  def account_exists
    if Account.find_by_id(account_id).nil?
      errors.add(:account_not_exists, 'Conta não encontrada')
    end
  end

  def account_number
    if account
      account.id
    end
  end

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :accounts
  has_many :partners
  has_one :legal_person
  has_one :physical_person
  
  enum tipo: [:physical, :legal]

  def get_address
    return legal_person.address if legal?
    physical_person.address if physical?
  end

  def get_account_name
    return legal_person.nome if legal?
    physical_person.nome if physical?
  end


end

app/models/physical_person.rb
class PhysicalPerson < ActiveRecord::Base
  belongs_to :person
  belongs_to :address

  before_create :set_physical, :set_address

  validates :nome, length: { minimum: 3, maximum: 200 }
  validates :cpf, length: { minimum: 9, maximum: 9 }
  validates :cpf, uniqueness: true

  def set_physical
    self.person = Person.create!(tipo: Person.tipos[:physical])
  end

  def set_address
    self.address = Address.create!
  end

end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController

  before_action :authorize_manager
  before_action :set_manager

  def index

  end

  private

  def set_manager
    @manager = Manager.find session[:manager_id]
  end


end

app/controllers/person_controller.rb
include AccountsHelper

class PersonController < ApplicationController

  before_action :authorize_person
  before_action :set_person

  def index

  end

  private

  def set_person
    @person = Person.find(session[:person_id])
  end

end

app/controllers/physical_people_controller.rb
class PhysicalPeopleController < ApplicationController

  before_action :authorize_manager
  before_action :set_physical_person, only: [:show, :edit, :update, :destroy]

  def index
    @physical_people = PhysicalPerson.all
  end

  def show
  end

  def new
    @physical_person = PhysicalPerson.new
  end

  def edit
  end

  def create
    @physical_person = PhysicalPerson.new(physical_person_params)

    respond_to do |format|
      if @physical_person.save
        format.html { redirect_to @physical_person, notice: 'Pessoa física cadastrada.' }
        format.json { render :show, status: :created, location: @physical_person }
      else
        format.html { render :new }
        format.json { render json: @physical_person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @physical_person.update(physical_person_params)
        format.html { redirect_to @physical_person, notice: 'Pessoa física editada.' }
        format.json { render :show, status: :ok, location: @physical_person }
      else
        format.html { render :edit }
        format.json { render json: @physical_person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @physical_person.destroy
    respond_to do |format|
      format.html { redirect_to physical_people_url, notice: 'Pessoa física excluída.' }
      format.json { head :no_content }
    end
  end

  private
    def set_physical_person
      @physical_person = PhysicalPerson.find(params[:id])
    end

    def physical_person_params
      params.require(:physical_person).permit(:cpf, :nome, :nascimento)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def agencies_options
    Agency.all.map { |agency| [agency.nome, agency.id] }
  end

  def tipos_options
    [
        ['Conta Corrente', Account.tipos[:corrente]],
        ['Conta Poupança', Account.tipos[:poupanca]]
    ]
  end

  def physical_people_options
    PhysicalPerson.includes(:person).all.map { |p| [p.nome, p.person.id] }
  end

  def legal_people_options
    LegalPerson.includes(:person).all.map { |p| [p.nome, p.person.id] }
  end

  def ac_number(account)
    '%05d' % account.id
  end

  def ac_type(account)
    account.tipo
  end

  def monetize(number)
    number = number.to_f

    "R$#{number.round(2)}"
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/agencies_helper.rb
module AgenciesHelper

  def agency_number (agency)
    '%04d' % agency.numero
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legal_people_helper.rb
module LegalPeopleHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/physical_people_helper.rb
module PhysicalPeopleHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/physical_people/_form.html.haml
= form_for @physical_person do |f|
  - if @physical_person.errors.any?
    .alert.alert-danger
      %h2= "Erro ao salvar."
      %ul
        - @physical_person.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :nome, 'Nome Completo: '
    = f.text_field :nome, class: 'form-control'
  .form-group
    = f.label :cpf, 'CPF: '
    = f.text_field :cpf, class: 'form-control'
  .form-inline
    = f.label :nascimento
    = f.date_select :nascimento, { order: [:day, :month, :year] }, { class: 'form-control' }

  .actions
    = f.submit 'Salvar', class: 'btn btn-success'

app/views/physical_people/edit.html.haml
= render 'manager/navigation'

.row
  .thumbnail.thumb-center
    .caption
      = link_to 'Voltar', physical_people_path

      %h1 Editar Pessoa Física

      = render 'form'

app/views/physical_people/index.html.haml
= render 'manager/navigation'

.container-fluid
  %h1 Listando Pessoas Físicas

  %table.table.table-bordered
    %thead
      %tr
        %th Nome
        %th CPF
        %th.th-actions-crud

    %tbody
      - @physical_people.each do |physical_person|
        %tr
          %td= physical_person.nome
          %td= physical_person.cpf
          %td.text-center
            .btn-group
              = link_to physical_person, class: 'btn btn-default' do
                %i.glyphicon.glyphicon-edit
                Visualizar
              = link_to edit_physical_person_path(physical_person), class: 'btn btn-default' do
                %i.glyphicon.glyphicon-edit
                  Editar
              = link_to physical_person, :method => :delete, :data => { :confirm => 'Você tem certeza?' }, class: 'btn btn-default' do
                %i.glyphicon.glyphicon-remove
                  Remover
  %br

  = link_to new_physical_person_path, class: 'btn btn-info' do
    %i.glyphicon.glyphicon-plus
    Nova Pessoa Física
 

app/views/physical_people/new.html.haml
= render 'manager/navigation'

.row
  .thumbnail.thumb-center
    .caption
      = link_to 'Voltar', physical_people_path
      %h1 Nova Pessoa Física

      = render 'form'

app/views/physical_people/show.html.haml
= render 'manager/navigation'

.row
  .thumbnail.thumb-center
    .caption
      = link_to 'Voltar', physical_people_path

      %div
        %strong Nome:
        = @physical_person.nome
      %div
        %strong CPF:
        = @physical_person.cpf
      %div
        %strong Data de Nascimento:
        = @physical_person.nascimento
      %div.text-center
        .btn-group
          = link_to 'Endereço', address_path(@physical_person.address), class: 'btn btn-default'
          = link_to 'Editar', edit_physical_person_path(@physical_person), class: 'btn btn-default'