config/routes.rb
Rails.application.routes.draw do

  resources :partners
  root 'visitors#index'

  # Auth
  match 'auth/manager', to: 'visitors#manager', via: :post
  match 'auth/legal_person', to: 'visitors#legal_person', via: :post
  match 'auth/physical_person', to: 'visitors#physical_person', via: :post
  match 'auth/logout', to: 'visitors#logout', via: :get

  # Manager
  match 'manager', to: 'manager#index', via: :get

  # Person
  match 'person', to: 'person#index', via: :get

  # Agency
  resources :agencies

  # Account
  resources :accounts

  # Account Operation
  match '/account_operations/new/:account_id/:tipo', to: 'account_operations#new', via: :get, as: :new_account_operation
  match '/account_operations/', to: 'account_operations#create', via: :post, as: :save_account_operation
  match '/account_operations/:id', to: 'account_operations#show', via: :get, as: :account_operations

  # Physical Person
  resources :physical_people

  # Legal Person
  resources :legal_people

  # Address
  match 'addresses/:id', to: 'addresses#show', via: :get, as: :address
  match 'addresses/:id/edit', to: 'addresses#edit', via: :get, as: :edit_address
  match 'addresses/:id', to: 'addresses#update', via: :patch, as: :update_address

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :agency
  belongs_to :person

  validates :limite_cheque_esp, presence: true
  validate :incomplete_address

  enum tipo: [:corrente, :poupanca]

  def incomplete_address
    address = person.get_address

    #if [address.rua, address.cidade, address.cep, address.uf.blank?, address.numero.blank?].any?(&:blank?)
    if address.cidade.blank? or address.cep.blank? or address.rua.blank? or address.uf.blank? or address.numero.blank?
      errors.add(:incomplete_address, 'Endereço incompleto')
    end
  end

  def last_operations
    AccountOperation
        .includes(person: [:physical_person, :legal_person])
        .where(account_id: id)
        .order(created_at: :desc)
        .limit(10)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :authorize_manager, except: :show
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.all
  end

  def show
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.tipo = params[:tipo].to_i

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Conta criada.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Conta editada.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Conta excluída.' }
      format.json { head :no_content }
    end
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:agency_id, :person_id, :limite_cheque_esp)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def agencies_options
    Agency.all.map { |agency| [agency.nome, agency.id] }
  end

  def tipos_options
    [
        ['Conta Corrente', Account.tipos[:corrente]],
        ['Conta Poupança', Account.tipos[:poupanca]]
    ]
  end

  def physical_people_options
    PhysicalPerson.includes(:person).all.map { |p| [p.nome, p.person.id] }
  end

  def legal_people_options
    LegalPerson.includes(:person).all.map { |p| [p.nome, p.person.id] }
  end

  def ac_number(account)
    '%05d' % account.id
  end

  def ac_type(account)
    account.tipo
  end

  def monetize(number)
    number = number.to_f

    "R$#{number.round(2)}"
  end

end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    .alert.alert-danger
      %h2= "Erro ao salvar."
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :agency_id, 'Agência'
    = f.select :agency_id, options_for_select(agencies_options), {}, class: 'form-control'
  .form-group
    = f.label :tipo, 'Tipo de Conta'
    = f.select :tipo, options_for_select(tipos_options), {}, class: 'form-control'
  .form-group
    = f.label :limite_cheque_esp, 'Limite de Cheque Especial'
    = f.text_field :limite_cheque_esp, class: 'form-control'

  .form-group
    = f.label :person_id, 'Cliente'
    = f.select :person_id, options_for_select(physical_people_options+legal_people_options), {}, class: 'form-control'
    - if @account.errors.messages.include? :incomplete_address
      = link_to 'Corrigir Endereço', edit_address_path(@account.person.id), target: '_blank'
  .actions
    = f.submit 'Salvar', class: 'btn btn-success'

app/views/accounts/edit.html.haml
= render 'manager/navigation'

.row
  .thumbnail.thumb-center
    .caption
      = link_to 'Voltar', accounts_path

      %h1 Editar conta

      = render 'form'

app/views/accounts/index.html.haml
= render 'manager/navigation'

.container-fluid
  %h1 Listando Contas

  %table.table.table-bordered
    %thead
      %tr
      %th Número
      %th Tipo
      %th Agência
      %th.th-actions-crud
    %tbody
      - @accounts.each do |account|
        %tr
          %td= account.id
          %td= account.tipo
          %td= account.agency.nome
          %td.text-center
            .btn-group
              = link_to account, class: 'btn btn-default' do
                %i.glyphicon.glyphicon-edit
                Visualizar
              = link_to edit_account_path(account), class: 'btn btn-default' do
                %i.glyphicon.glyphicon-edit
                  Editar
              = link_to account, :method => :delete, :data => { :confirm => 'Você tem certeza?' }, class: 'btn btn-default' do
                %i.glyphicon.glyphicon-remove
                  Remover

  = link_to new_account_path, class: 'btn btn-info' do
    %i.glyphicon.glyphicon-plus
    Abrir Conta

app/views/accounts/new.html.haml
= render 'manager/navigation'

.row
  .thumbnail.thumb-center
    .caption
      = link_to 'Voltar', accounts_path
      %h1 Nova Conta

      = render 'form'

app/views/accounts/show.html.haml
= render 'manager/navigation' if session[:manager_id]
= render 'person/navigation' if session[:person_id]

.container-fluid
  = link_to 'Voltar', person_path if session[:person_id]

  .thumbnail
    .caption.text-center
      %div
        %strong Número da conta:
        = "#{agency_number(@account.agency)}-#{ac_number(@account)}"
      %div
        %strong Tipo da conta:
        = @account.tipo.capitalize
      %div
        %strong Saldo:
        = monetize @account.saldo
        - if session[:manager_id]
          %div
            .btn-group
              = link_to edit_account_path(@account), class: 'btn btn-default' do
                %i.glyphicon.glyphicon-edit
                Editar
              = link_to accounts_path, class: 'btn btn-default' do
                %i.glyphicon.glyphicon-arrow-left
                Voltar

        - if session[:person_id]
          %div
            .btn-group
              = link_to 'Saque', new_account_operation_path(@account.id, AccountOperation::tipos[:saque]), class: 'btn btn-default'
              = link_to 'Depósito', new_account_operation_path(@account.id, AccountOperation::tipos[:deposito]), class: 'btn btn-default'

  %h4 Últimos Lançamentos

  %table.table.table-condensed.table-striped
    %tr
      %th Pessoa
      %th Ação
      %th Valor
    - @account.last_operations.each do |operation|
      %tr
        %td= operation.person.get_account_name
        %td= operation.tipo.capitalize
        %td= monetize operation.amount